// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAYfK_bhPPhb80ON5-KSYtRG2RhKpCbB8',
    appId: '1:732171665921:web:e2524b7df4c72f0e453600',
    messagingSenderId: '732171665921',
    projectId: 'turf-f0104',
    authDomain: 'turf-f0104.firebaseapp.com',
    storageBucket: 'turf-f0104.firebasestorage.app',
    measurementId: 'G-WM534XQZPT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu1uu459uIksSsDTcXF1MQIOQ0rMxIe1Y',
    appId: '1:732171665921:android:9ea1a7633fbc15c9453600',
    messagingSenderId: '732171665921',
    projectId: 'turf-f0104',
    storageBucket: 'turf-f0104.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATag06CgArNP_JD7iBJ6lzZxUKmvRczig',
    appId: '1:732171665921:ios:33639fb3379f3c7e453600',
    messagingSenderId: '732171665921',
    projectId: 'turf-f0104',
    storageBucket: 'turf-f0104.firebasestorage.app',
    iosBundleId: 'com.codewitzz.turfClient',
  );
}
